"""Descriptive fact sheets of the loadable datasets: what the data-blind Scout may know (decision Q5).

Allowed: coverage, instrument counts, typical volatility and liquidity, correlations between asset classes.
Never: mean returns, Sharpe ratios, drawdowns, anything conditional on a signal. Everything is computed on
the dev part only (rows before `holdout_from`), so the sheets carry no holdout information either.

The sheets are framework output, built by labcore (`lab factsheets`) and cached per catalog hash under
`LAB_HOME/cache`. Agent workspaces get a copy of the markdown.
"""

import hashlib
import warnings
from pathlib import Path

import numpy as np

from lab.framework import catalog, data

VERSION = 1
ETF_TOP = 60
SPIKE = 0.4
DAY = np.timedelta64(1, "D")
CRYPTO_TOP = 30
# Reference set for the cross-class correlation table (weekly returns, Friday to Friday).
REFERENCE = {"SPY": "US large caps", "QQQ": "Nasdaq 100", "IWM": "US small caps", "EFA": "developed ex-US",
             "EEM": "emerging markets", "TLT": "long Treasuries", "IEF": "7-10y Treasuries",
             "LQD": "IG credit", "HYG": "high yield", "GLD": "gold", "DBC": "commodities", "VNQ": "US REITs",
             "UUP": "US dollar", "BTCUSDT": "bitcoin", "ETHUSDT": "ether"}


def cache_path(home: Path, catalog_path: Path) -> Path:
    key = hashlib.sha256(catalog_path.read_bytes() + f"v{VERSION}".encode()).hexdigest()[:12]
    return home / "cache" / f"factsheets_{key}.md"


def get(home: Path, catalog_path: Path, rebuild: bool = False) -> Path:
    """Path of the current fact sheets, built if missing (a few seconds, < 1 GB RAM)."""
    out = cache_path(home, catalog_path)
    if rebuild or not out.exists():
        out.parent.mkdir(parents=True, exist_ok=True)
        tmp = out.with_suffix(".tmp")
        tmp.write_text(build(catalog_path))
        tmp.replace(out)
    return out


def build(catalog_path: Path) -> str:
    cat = catalog.load(catalog_path)
    parts = [
        "# Dataset fact sheets (dev period only, descriptive)",
        "",
        "Generated by the framework from the dev part of each dataset. They describe what exists and how it",
        "behaves in general (coverage, volatility, liquidity, correlations). They deliberately contain no",
        "returns, Sharpe ratios or signal-conditional numbers: you are data-blind by design, the gate runner",
        "is the only place where a hypothesis meets the data.",
        "",
    ]
    weekly: dict[str, tuple[np.ndarray, np.ndarray]] = {}
    if "sharadar_sfp" in cat:
        text, w = _etf_sheet(cat["sharadar_sfp"])
        parts.append(text)
        weekly |= w
    if "binance_spot_1d" in cat:
        text, w = _crypto_sheet(cat["binance_spot_1d"])
        parts.append(text)
        weekly |= w
    parts.append(_correlations(weekly, min(data.as_date(cat[d]["holdout_from"]) for d in
                                           ("sharadar_sfp", "binance_spot_1d") if d in cat)))
    parts.append(_no_loader(cat))
    return "\n".join(parts) + "\n"


# ---------------------------------------------------------------------------- per dataset

def _etf_sheet(entry: dict) -> tuple[str, dict]:
    import polars as pl

    src = data.DATA_ROOT / "parquet" / data.SHARADAR
    holdout = data.as_date(entry["holdout_from"])
    hd = holdout.astype(object)
    names = (pl.read_parquet(src / "tickers.parquet", columns=["table", "ticker", "name", "category"])
             .filter(pl.col("table") == "SFP").unique("ticker").select("ticker", "name", "category"))
    px = (pl.scan_parquet(src / "funds.parquet").filter(pl.col("date") < hd)
          .select("ticker", "date", "closeadj", "closeunadj", "volume"))
    years = [2000, 2005, 2010, 2015, int(str(holdout)[:4]) - 1]
    counts = (px.filter(pl.col("date").dt.year().is_in(years)).group_by(pl.col("date").dt.year().alias("y"))
              .agg(pl.col("ticker").n_unique().alias("n")).sort("y").collect())
    last_year = years[-1]
    liq = (px.filter(pl.col("date").dt.year() == last_year)
           .group_by("ticker").agg((pl.col("closeunadj") * pl.col("volume")).median().alias("dv"))
           .sort("dv", descending=True).head(ETF_TOP).collect())
    top = liq["ticker"].to_list()
    hist = (px.filter(pl.col("ticker").is_in(top + [t for t in REFERENCE if not t.endswith("USDT")]))
            .sort("ticker", "date").collect())
    lr = (pl.col("closeadj") / pl.col("closeadj").shift(1).over("ticker")).log()
    hist = hist.with_columns(lr.alias("lr")).with_columns(   # one-day price spikes that reverse next day
        ((pl.col("lr").abs() > SPIKE) & ((pl.col("lr") + pl.col("lr").shift(-1).over("ticker")).abs() < 0.1))
        .alias("spike"))
    hist = hist.with_columns((pl.col("spike") | pl.col("spike").shift(1).over("ticker")).fill_null(False))
    stats = (hist.group_by("ticker").agg(
        pl.col("date").min().alias("first"),
        (pl.col("lr").filter(~pl.col("spike")).std() * np.sqrt(252)).alias("vol"),
        pl.col("spike").sum().alias("spikes")))
    t = liq.join(stats, on="ticker").join(names, on="ticker", how="left").sort("dv", descending=True)

    lines = [f"## sharadar_sfp (US ETFs and funds), dev {entry['range'][0]} .. {holdout - DAY}", "",
             "Funds with a price in the year: " + ", ".join(f"{r['y']}: {r['n']}" for r in counts.iter_rows(named=True)),
             "(includes ETNs, closed-end funds and leveraged products; many ETFs start only after 2003-2007).",
             f"Data quality: some funds have one-day price spikes in the adjusted close (a move > {SPIKE:.0%} in log",
             "terms that reverses the next day, e.g. SSO on 2014-06-24). The gate runner does not clean them.", "",
             f"Top {ETF_TOP} by median daily dollar volume in {last_year} (vol = annualized volatility of daily",
             "log total returns over the dev period from the first price, without one-day spikes):", "",
             "| ticker | name | category | first price | vol | median $vol " + str(last_year) + " |",
             "|---|---|---|---|---|---|"]
    for r in t.iter_rows(named=True):
        lines.append(f"| {r['ticker']} | {(r['name'] or '')[:48]} | {r['category']} | {r['first']} | "
                     f"{r['vol']:.0%} | {_money(r['dv'])} |")
    weekly = {}
    for tk in REFERENCE:
        if tk.endswith("USDT"):
            continue
        s = hist.filter(pl.col("ticker") == tk)
        if s.height:
            weekly[tk] = _weekly(s["date"].to_numpy().astype("datetime64[D]"), s["closeadj"].to_numpy())
    return "\n".join(lines) + "\n", weekly


def _crypto_sheet(entry: dict) -> tuple[str, dict]:
    v = data.binance_spot(None)
    holdout = data.as_date(entry["holdout_from"])
    v = v.between(None, holdout - DAY)
    years = sorted({int(str(d)[:4]) for d in v.dates})
    counts = []
    for y in years:
        rows = (v.dates >= np.datetime64(f"{y}-01-01")) & (v.dates <= np.datetime64(f"{y}-12-31"))
        counts.append((y, int(v.listed[rows].any(axis=0).sum())))
    last = (v.dates >= np.datetime64(f"{years[-1]}-01-01"))
    dv = np.where(v.listed[last], v.dollar_volume[last], np.nan)
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", RuntimeWarning)   # pairs never listed in that year
        med = np.nanmedian(dv, axis=0)
    order = [j for j in np.argsort(-np.nan_to_num(med, nan=-1)) if np.isfinite(med[j])][:CRYPTO_TOP]
    lr = np.log((1 + v.ret_co) * (1 + v.ret_oc))
    lines = [f"## binance_spot_1d (Binance spot USDT pairs), dev {v.dates[0]} .. {v.dates[-1]}", "",
             "Pairs listed at some point in the year: " + ", ".join(f"{y}: {n}" for y, n in counts),
             "(stablecoins and wrapped assets excluded; delisted pairs only partly present).", "",
             f"Top {CRYPTO_TOP} by median daily dollar volume in {years[-1]} (vol = annualized, 365 days, of daily",
             "log returns while listed):", "",
             f"| pair | first day | vol | median $vol {years[-1]} |", "|---|---|---|---|"]
    for j in order:
        rows = v.listed[:, j]
        first = v.dates[np.argmax(rows)]
        vol = np.nanstd(lr[rows, j]) * np.sqrt(365)
        lines.append(f"| {v.instruments[j]} | {first} | {vol:.0%} | {_money(med[j])} |")
    top20 = order[:20]
    both = v.listed[:, top20].all(axis=1)
    c = np.corrcoef(lr[both][:, top20].T)
    off = c[~np.eye(len(top20), dtype=bool)]
    lines += ["", f"Median pairwise correlation of daily returns among the top 20 (days where all 20 trade, "
              f"n = {int(both.sum())}): {np.median(off):.2f}."]
    weekly = {}
    for tk in ("BTCUSDT", "ETHUSDT"):
        j = v.col(tk)
        weekly[tk] = _weekly(v.dates[v.listed[:, j]], np.cumprod(np.exp(lr[v.listed[:, j], j])))
    return "\n".join(lines) + "\n", weekly


def _correlations(weekly: dict, until: np.datetime64) -> str:
    tickers = [t for t in REFERENCE if t in weekly]
    lines = ["## Cross-class correlations", "",
             "Correlation of weekly returns (Friday close to Friday close; crypto at 00:00 UTC Saturday), each pair",
             f"over its common dev weeks (up to {until - DAY}). n = weeks of the shortest series in the pair.", "",
             "| | " + " | ".join(tickers) + " |", "|---" * (len(tickers) + 1) + "|"]
    for a in tickers:
        row = []
        for b in tickers:
            da, ra = weekly[a]
            db, rb = weekly[b]
            common, ia, ib = np.intersect1d(da, db, return_indices=True)
            row.append(f"{np.corrcoef(ra[ia], rb[ib])[0, 1]:.2f}" if len(common) >= 52 else "")
        lines.append(f"| **{a}** | " + " | ".join(row) + " |")
    lines += ["", "Reference set: " + "; ".join(f"{t} = {d}" for t, d in REFERENCE.items() if t in weekly) + "."]
    return "\n".join(lines) + "\n"


def _no_loader(cat: dict) -> str:
    lines = ["## Datasets without a loader", "",
             "In the catalog, but the gate runner cannot load them yet. A hypothesis that needs them stays",
             "BLOCKED_DATA and the owner is asked; see catalog.yaml for coverage and biases.", ""]
    lines += [f"- {d['id']} ({d['asset_class']}, {d['frequency']}, {d['range'][0]} .. {d['range'][1]})"
              for d in cat.values() if not d.get("loader")]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------- helpers

def _weekly(dates: np.ndarray, level: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Weekly log returns between the last observations of consecutive weeks, keyed by the week's Friday."""
    dates = dates.astype("datetime64[D]")
    friday = dates + ((4 - (dates.astype(np.int64) - 4) % 7) % 7).astype("timedelta64[D]")   # 1970-01-01 = Thu
    last = np.r_[friday[1:] != friday[:-1], True]
    wk, lvl = friday[last], np.log(level[last])
    return wk[1:], np.diff(lvl)


def _money(x: float) -> str:
    for unit, div in (("bn", 1e9), ("M", 1e6), ("k", 1e3)):
        if x >= div:
            return f"{x / div:.1f} {unit}"
    return f"{x:.0f}"
