"""Lessons: the Librarian's qualitative record of what each hypothesis taught, fed back to the Scout.

Lessons are words, not numbers. The Librarian sees full gate metrics; the Scout must not, because proposing
the next idea from the dev-period metrics of the last one is an adaptive search on dev data that no trial
counter sees. So a lesson with decimals or percentages is refused, and the Scout only reads the rendered file
`lab/knowledge/lessons.md` (regenerated by the framework from the LESSON messages, newest per hypothesis).
"""

import json
import re

from lab.framework.blackboard import Lab, LabError
from lab.framework.states import TERMINAL, S

NUMBERS = re.compile(r"\d+[.,]\d+|\d+\s*%|\bx\s*\d|\d+\s*x\b|(?<![\w-])[-+−]\s?\d")   # H-0001 is fine
TEXT_FIELDS = ("instruments", "outcome", "lesson", "avoid", "open_questions", "family_merge")
LESSON_STATES = TERMINAL | {S.GATE_3, S.SKEPTIC_REVIEW, S.HOLDOUT, S.PAPER, S.LIVE_CANDIDATE}


def check(lab: Lab, hid: str, payload: dict) -> None:
    h = lab.hypothesis(hid)
    if S(h["status"]) not in LESSON_STATES:
        raise LabError(f"{hid} is {h['status']}: lessons are written once a hypothesis is decided or past G3")
    if payload["family"] != h["family"]:
        raise LabError(f"family {payload['family']!r} is not {hid}'s family {h['family']!r}")
    for f in TEXT_FIELDS:
        m = NUMBERS.search(payload.get(f) or "")
        if m:
            raise LabError(f"{f}: {m.group(0)!r} looks like a metric; lessons are qualitative (no decimals, "
                           "percentages, multiples or signed numbers)")


def path(lab: Lab):
    return lab.paths.lab / "knowledge" / "lessons.md"


def render(lab: Lab) -> None:
    rows = lab.con.execute("SELECT m.* FROM messages m JOIN lessons l ON l.message_id = m.id ORDER BY m.id").fetchall()
    latest = {}
    for r in rows:
        latest[r["hypothesis_id"]] = (r, json.loads(r["payload_json"]))
    out = ["# Lessons from the lab's hypotheses", "",
           "Written by the Librarian, rendered by the framework. Qualitative on purpose: no metrics.", ""]
    for hid in sorted(latest):
        r, p = latest[hid]
        h = lab.hypothesis(hid)
        out += [f"## {hid} – {h['title']}", "",
                f"- family: `{p['family']}` · mechanism: {p['mechanism_class']}"
                + (f" · instruments: {p['instruments']}" if p.get("instruments") else ""),
                f"- outcome: {p['outcome']}", f"- lesson: {p['lesson']}"]
        out += [f"- {k.replace('_', ' ')}: {p[k]}" for k in ("avoid", "open_questions") if p.get(k)]
        if p.get("related"):
            out.append(f"- related: {', '.join(p['related'])}")
        out.append("")
    f = path(lab)
    f.parent.mkdir(parents=True, exist_ok=True)
    f.write_text("\n".join(out))
